version: '3.5'
services:
  postgres:
    image: postgres:latest
    hostname: db
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rinha
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c max_connections=200 -c shared_buffers=200MB -c synchronous_commit=off -c fsync=off -c full_page_writes=off
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: '0.70'
          memory: 250MB

  app3: &api
    image: api-backend-native
    hostname: app3
    container_name: app3
    environment:
      - VIRTUAL_THREADS_ENABLED=true
      - SERVER_HTTP_CONN_TIMEOUT=500
      - SERVER_MAX_THREADS=50
      - SERVER_MAX_CONNECTIONS=200
      - DB_POOL_MAX_POOL=10
      - DB_IDLE_TIMEOUT=30000
      - DB_CONNECTION_TIMEOUT=1000
      - DB_HOST=postgres
      - DB_DATABASE=rinha
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - SERVER_PORT=8083
    ports:
      - "8083:8080"
    depends_on:
      postgres:
        condition: service_healthy

    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: 128MB

  app2:
    <<: *api
    hostname: app2
    container_name: app2
    environment:
      - VIRTUAL_THREADS_ENABLED=true
      - SERVER_HTTP_CONN_TIMEOUT=500
      - SERVER_MAX_THREADS=50
      - SERVER_MAX_CONNECTIONS=200
      - DB_POOL_MAX_POOL=10
      - DB_IDLE_TIMEOUT=30000
      - DB_CONNECTION_TIMEOUT=1000
      - DB_HOST=postgres
      - DB_DATABASE=rinha
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - SERVER_PORT=8082
    ports:
      - "8082:8080"

  nginx:
    image: nginx:latest
    hostname: nginx
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app3
      - app2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: 20MB

networks:
  default:
    driver: bridge
    name: java-is-goat