version: '3'

services:
  db:
    image: postgres:latest
    restart: always
    hostname: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rinha

    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    command: postgres -c max_connections=200 -c shared_buffers=100MB -c synchronous_commit=off -c fsync=off -c full_page_writes=off

    networks:
      - rinha
    deploy:
      resources:
        limits:
          cpus: '0.7'
          memory: 200M

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
    networks:
      - rinha
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 10M

  app1:
    image: api-backend-native
    ports:
      - "8001:8080"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    depends_on:
      - db
    networks:
      - rinha
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: 150M

  app2:
    image: api-backend-native
    ports:
      - "8002:8080"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    depends_on:
      - db
    networks:
      - rinha
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: 150M
#
#  pgadmin:
#    image: dpage/pgadmin4
#    restart: always
#    ports:
#      - "5050:80"
#    environment:
#      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
#      - PGADMIN_DEFAULT_PASSWORD=admin
#    networks:
#      - rinha

networks:
  rinha:
    driver: bridge