spring:
  application:
    name: java-is-goat
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://db/rinha
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: false